### ISSUE TITLE
過去のGGJまとめページを作る

### ISSUE THREAD

**Issue by giginet** [kawazrepos/Kawaz3rd#1050]
毎年言ってる気がする

作品までまとめるのは大変だけど、配信動画ぐらいは埋め込まれてて良いのではないか

@miio @Clpsplug

**Comment by giginet** [comment]
今年こそ作りたいぞ

**Comment by tunacook** [comment]
# 2014
http://www.ustream.tv/recorded/43104809
http://www.ustream.tv/recorded/43107548
http://www.ustream.tv/recorded/43107805

# 2015
http://www.ustream.tv/recorded/58042775


# 2016
http://www.ustream.tv/recorded/82288691

**Comment by tunacook** [comment]
とーこさんorらいだこさんor和牛先生が写真撮ってたイメージがある

**Comment by tunacook** [comment]
http://www.ustream.tv/search?q=Global%20Game%20Jam%20Sapporo

**Comment by tunacook** [comment]
9:05] 
ここらへんに2012年のustのURLらしきものがあるが、おそらくustreamの仕様変更とkawazustの設定をサボったせいで消滅したっぽいな
http://togetter.com/li/252373?page=4
 
Togetter
Global Game Jam 2012 ～札幌会場の様子～ (4ページ目)
Global Game Jam 2012()が閉幕しました。全てのゲームはダウンロードして実際に遊ぶことができます。 日本会場は、札幌、仙台，東京（東京工科大，NII），京都、大阪，福岡で開催され..

[9:07] 
電子の彼方へ消え去ったのだ

[9:11] 
2012だけSapporo6hさんじゃなくて自前（kawazust）でやろうとしたのかもね（私参加してないや）

[9:11] 
で、ustreamの仕様変更に飲み込まれたという

**Comment by tunacook** [comment]
誰もやらなそうだしやるかな

@giginet mdで書いて普通にリポジトリに含めれば良い？

**Comment by giginet** [comment]
本当はそれだけじゃダメなんだけど、組み込む部分は僕がやるので、mdだけ作っておいてください。

https://github.com/kawazrepos/Kawaz3rd/tree/develop/src/templates/markdown

**Comment by tunacook** [comment]
OK
