### ISSUE TITLE
会員登録未処理の人が「退会済メンバー一覧」にいる

### ISSUE THREAD

**Issue by tunacook** [kawazrepos/Kawaz3rd#1061]
![https://i.gyazo.com/61f2b90aa474579864c64743d94e10ba.png](https://i.gyazo.com/61f2b90aa474579864c64743d94e10ba.png)

tetsuo_liederさん

**Comment by giginet** [comment]
仕組み的にしょうがないから仕様にしようか

**Comment by tunacook** [comment]
:ok_hand:
