### ISSUE TITLE
作品ページでブラウザゲーのリンクがdownloadになってるのは違和感がある

### ISSUE THREAD

**Issue by giginet** [kawazrepos/Kawaz3rd#1064]
プラットフォームがブラウザ、かつURLリリースの場合は「今すぐ遊ぶ！」とかになっていた方が自然そう

**Comment by tunacook** [comment]
これってサーバアプリ側でやることになりそうです？　情報取ってこれるのであればテンプレートでやっちゃってもいい気がしてたけど

**Comment by giginet** [comment]
（厳密にはテンプレートもサーバーサイドなんだけど）テンプレートでできるよ！

ただ、メソッド生やしてしまった方が綺麗な気がする

`release.is_play_now`とか

**Comment by giginet** [comment]
テストもできるしね

**Comment by tunacook** [comment]
hai

**Comment by giginet** [comment]
テスト含め瞬殺できるから帰ったらやっておくよ
