### ISSUE TITLE
作品のトレイラーにYouTubeの短縮URLを使用できない

### ISSUE THREAD

**Issue by Clpsplug** [kawazrepos/Kawaz3rd#1102]
# Steps to Reproduce

1. YouTubeで、共有時にドメインが`youtu.be`の短縮URLをコピー
2. これを作品のトレイラーに設定する

# Expected

作品画面でyoutubeのembedが発動し、トレイラーを観ることができる

# What Actually Happened

入力した短縮URLがそのまま表示され、トレイラーが表示されるはずだった部分が大きな余白になる

# Remarks

`youtu.be/ABCDE` の`ABCDE`の部分は動画IDそのもの。

**Comment by giginet** [comment]
https://github.com/kawazrepos/Kawaz3rd/blob/develop/src/kawaz/apps/kfm/extras/youtube.py#L7

ここのregexを書き加えてテスト書けばすぐ直りそう
