### ISSUE TITLE
django-filter 1.00 対応

### ISSUE THREAD

**Issue by lambdalisue** [kawazrepos/Kawaz3rd#1106]
エラー出る。対応中

**Comment by lambdalisue** [comment]
AssertionError: Setting 'Meta.model' without either 'Meta.fields' or 'Meta.exclude' has been deprecated since 0.15.0 and is now disallowed. Add an explicit'Meta.fields' or 'Meta.exclude' to the PersonaFilter class.

**Comment by giginet** [comment]
https://github.com/carltongibson/django-filter/blob/1.0.0/docs/guide/migration.txt

migration noteあるやん
この通りに作業すればシュッと直りそう

**Comment by lambdalisue** [comment]
https://django-filter.readthedocs.io/en/latest/guide/migration.html こっちのほうが見やすい
