### ISSUE TITLE
Let's Encrypt で SSL

### ISSUE THREAD

**Issue by raa0121** [kawazrepos/Kawaz3rd#1117]
してみたい

**Comment by raa0121** [comment]
埋め込まれてるURLによっては、 //hogehuga.com/... な書き方にしないといけないかも  
あと、はてぶとかはリセットされちゃうはず

**Comment by miio** [comment]
https://speakerdeck.com/sorah/acmesmith-http2study8

そういえばこんなスライドを最近みたばっかだった

**Comment by giginet** [comment]
SSL対応はしたいねー

**Comment by miio** [comment]
そういえばポータルのほう、裏でインスタンス差替をカジュアルにできたらいいなと思ってLB挟んでるからLBに証明書セットしないとダメなんだったかな

http://cloud.nifty.com/api/rest/SetLoadBalancerListenerSSLCertificate.htm

DNSは今Route53だからacmesmithの導入のほうは割と簡単にいけるかも。

**Comment by giginet** [comment]
ATSでアプリ内ブラウザとかもSSL対応されてないページは表示できなくなりつつある模様
2017年にもなって非SSLだとページランクも下がりいろいろ良くないので最優先で対応していきたい

**Comment by giginet** [comment]
ぐう有脳 🎉 🎉 🎉
