### ISSUE TITLE
コメントも投稿前にプレビューしたい

### ISSUE THREAD

**Issue by tunacook** [kawazrepos/Kawaz3rd#1123]
githubみたいな感じで。本文記事のpreview機能と同じものを使う感じでいいかも

**Comment by giginet** [comment]
大分前にissue立ってた気がして重複済み

**Comment by tunacook** [comment]
なんかそんな気がしてたんだけどどのissueだっけ

**Comment by giginet** [comment]
https://github.com/kawazrepos/Kawaz3rd/issues/802

**Comment by tunacook** [comment]
thx
