### ISSUE TITLE
イベントページのログインして参加ボタンが効かない

### ISSUE THREAD

**Issue by giginet** [kawazrepos/Kawaz3rd#1146]

**Comment by tunacook** [comment]
「このイベントに参加するにはログインしている必要があります」じゃなかったっけ

翻訳ミスってる？　でもここらへん長らく弄ってないと思うけどなぁ

![81b08553183a4dc24b7d56de683feac5](https://cloud.githubusercontent.com/assets/1044064/24070364/5dfed0de-0bff-11e7-9d5d-3c65e7bb4526.png)

**Comment by Clpsplug** [comment]
そこは長すぎてボタンがでかくなってたので [PR !1100](https://github.com/kawazrepos/Kawaz3rd/pull/1100) で僕が変えてます
https://github.com/kawazrepos/Kawaz3rd/pull/1100/files#diff-aece386d56ba663b64169bd333b235d6L1575

**Comment by tunacook** [comment]
「ログインして～」だとそこからログイン画面に進める（その後イベントへリダイレクトする）ように見えちゃうから、また文言変えた方がいいかも

**Comment by tunacook** [comment]
なんかうまいこと考えておく

**Comment by giginet** [comment]
あー、なるほど
ボタンの挙動的に押したらログイン画面が出るのが正しいと思ってたけど、そもそも押せないのが正しい挙動で、文言変えたからわかりづらくなったってことか。
別にログイン画面に飛ばす意味ないから文言良い感じにするのが良いかもね

**Comment by tunacook** [comment]
なんかもうこれでいいんじゃない感

![](https://gyazo.com/c10a8cf6cb001b5f8576c1c3fc2808f4.png)

**Comment by giginet** [comment]
よさそう。PRください
