### ISSUE TITLE
issue ネルフ以上の場合何処かにgitのrevisionを表示

### ISSUE THREAD

**Issue by tunacook** [kawazrepos/Kawaz3rd#649]
![2014-11-24 11 57 27](https://cloud.githubusercontent.com/assets/1044064/5160507/22f416e8-73d1-11e4-99b2-1c1b90312afc.png)

ここかfooterかな

**Comment by giginet** [comment]
急にやる気が出たのでdjango-debug-toolbarのプラグインとして汎化中･･････

https://github.com/giginet/django-debug-toolbar-vcs-rev

**Comment by giginet** [comment]
1年越しにプラグインができた

https://github.com/giginet/django-debug-toolbar-vcs-info

あとは上記を2.xに対応させ、pipに公開したらKawaz側に実装するだけですね

![](https://gyazo.com/271b6c5e59730fd50abc17b94f263a64.png)

**Comment by giginet** [comment]
1年放置されてたissueが終わったぞ :+1:

**Comment by lambdalisue** [comment]
:+1:
