### ISSUE TITLE
migrationすると過去の履歴が全て死ぬ

### ISSUE THREAD

**Issue by giginet** [kawazrepos/Kawaz3rd#662]
@lambdalisue: 偶然だけどやばい問題に気付いた！！！

giginet [4:33 PM]
@lambdalisue: Activityのsnapshot

giginet [4:33 PM]
@lambdalisue: djangoのmigrationに追従しない

giginet [4:33 PM]
@lambdalisue: 要はカラム名変えたら死ぬ

giginet [4:34 PM]
@lambdalisue: 何かいい方法考えておいてください

giginet [4:34 PM]
オーバーテクノロジーの弊害やで

辛い問題。どうしよう。

**Comment by lambdalisue** [comment]
#856 で修正した
