### ISSUE TITLE
Markdown内の画像などの要素とのマージンが気になる

### ISSUE THREAD

**Issue by giginet** [kawazrepos/Kawaz3rd#827]
![](http://gyazo.com/634478c723d904aea6d7de8449b8bb9b.png)

この記事に限った話じゃないのですが

- img
- embed
- iframe
- blockquote
- audio
- video

などの要素と、本文間にマージンが少ないのが気になります

**Comment by tunacook** [comment]
あ、blockquoteへの適用されないや。追加するか。。
