### ISSUE TITLE
告知ページで編集ボタンを押すとログインに戻される

### ISSUE THREAD

**Issue by AttaQ** [kawazrepos/Kawaz3rd#838]
自身の作成した告知に表示される管理-このお知らせを編集を押すと
http://www.kawaz.org/registration/login/?next=/blogs/AttaQ/29/update/
このURLに飛ぶが  
http://gyazo.com/975bd65c250a6047e824b743dba340de
このようにログインした状態であってもログインの確認を求められ、  
ログインを押すと
http://www.kawaz.org/
へ飛ばされる。

**Comment by giginet** [comment]
パーミッションっぽい

**Comment by giginet** [comment]
これ、リンク先が間違ってただけだからもう直ってる気がする
