### ISSUE TITLE
承認メール送信後アクティベーション有効期限が切れた場合対応出来ない

### ISSUE THREAD

**Issue by AttaQ** [kawazrepos/Kawaz3rd#843]
マニュアルの例にある
- 承認メールを送ったのに放置されてる例
http://www.kawaz.org/helps/staff/registration/
http://gyazo.com/d2575be10af112ee183665ca5d3a016d
だが、

- Accept registrations of selected usersを選択して実行

がInternal Server Errorとなる

また、
- 選択されているユーザーに承認メールを再送信する  

もInternal Server Errorとなり、対応できない

**Comment by AttaQ** [comment]
対応確認。

**Comment by giginet** [comment]
[15:29] ぎぎ にゃん: 結論から言うと
		Kawazポータルにバグがあって、日本語ユーザー名が使えてたんだけど
		そのバグを潰した影響で
		登録データと実装に不整合があったから
		申請内容をこっち側で勝手に書き換えた
