### ISSUE TITLE
記事に対してコメントの範囲指定を行っている場合、コメントにスターをつけてもそれが反映される

### ISSUE THREAD

**Issue by AttaQ** [kawazrepos/Kawaz3rd#847]
![default](https://cloud.githubusercontent.com/assets/7066604/6097356/d0296c50-affe-11e4-9d78-b1f92e398f05.png)
このように、本文中の文章に対して範囲指定を行っていてもコメントに引用したスターをつけられてしまう

**Comment by giginet** [comment]
2ndからの仕様です
