### ISSUE TITLE
スマホレイアウトのイベント一覧画面でイベントカテゴリ名が長いとちょん切れる

### ISSUE THREAD

**Issue by tunacook** [kawazrepos/Kawaz3rd#864]
bootstrapのカラム数値変更案件

![slack_for_ios_upload_1024](https://cloud.githubusercontent.com/assets/1044064/6705408/ffafe100-cd97-11e4-9f2a-90983fe2fd7c.png)

**Comment by giginet** [comment]
@tunacook 直すの面倒だし、イベントカテゴリ名は管理者権限でしか直せないので運用でカバーしましょうか。
ゲームジャム・ハッカソンを「ゲームジャム」にすると良さそう？
あとはスキーマ側で最長文字列を設定しておくと尚良し

**Comment by tunacook** [comment]
@giginet ネルフ権限だとセントラルドグマからカテゴリ直せないのでゼーレのどなたかお願いします
