### ISSUE TITLE
メンバー加入条件を規約として明文化する

### ISSUE THREAD

**Issue by giginet** [kawazrepos/Kawaz3rd#883]
- [ ] 札幌民以外の扱いについて考える（知り合いならアカウント発行可 or 知り合いなら加入可能？）

**Comment by AttaQ** [comment]
現状
http://www.kawaz.org/rules/  
>Kawazメンバー以外がプロジェクトに携わる上でポータルのアカウントが必要な場合は
参加条件に満たない場合でも特例としてポータルサイトなどのアカウントを発行致します
（例：あるプロジェクトメンバーの友人にBGMを発注しているが、東京に住んでおり、ミーティングへの参加が不可能である、など）。

他、札幌在住ではない顔なじみの登録を承認した前例は有り。

**Comment by tunacook** [comment]
明文化されてるのでclose
