### ISSUE TITLE
メールの署名を@lyrica＆@cplug にする

### ISSUE THREAD

**Issue by tunacook** [kawazrepos/Kawaz3rd#889]
名前IDは要確認
grep置換無双

**Comment by tunacook** [comment]
-------------------------------------------------------
札幌ゲーム製作者コミュニティ - Kawaz

ホームページ: http://www.kawaz.org
責任者: AttaQ
連絡先: webmaster@kawaz.org
-------------------------------------------------------

**Comment by miio** [comment]
責任者のところ、むしろオミットしちゃってよいのではなかろうか（変わる度に対応するのもつらそう）

**Comment by giginet** [comment]
`settings.py`に`GEEKDRUMS`みたいな設定作って一括変更できるようにするみたいなissue出てた気がする

https://github.com/kawazrepos/Kawaz3rd/issues/708

**Comment by tunacook** [comment]
メールテンプレートをgiginet->AttaQに置換する際に話題になったけど、いつでもいいよねーと後回しだった気がしている

気が向いたら対応
