### ISSUE TITLE
lessc/coffee がインストールされていなくても動くようにする or インストールが必要なことを記載する

### ISSUE THREAD

**Issue by lambdalisue** [kawazrepos/Kawaz3rd#941]
入ってなくても動くように作ってた気がするけど気のせいだったのか。
入ってなくても動く or ドキュメント化

あと coffee も

**Comment by giginet** [comment]
django-compress使ってるので、無しで動かすのはリポジトリにコンパイル後の物を含まないと不可能

ドキュメントには必須なことが記載済み

**Comment by lambdalisue** [comment]
あれ？書いてあったけ？どこ？
