### ISSUE TITLE
新規会員登録で規約に同意するボタンのローカライズがされてない

### ISSUE THREAD

**Issue by giginet** [kawazrepos/Kawaz3rd#953]
django-inspectional-registrationの問題？

**Comment by giginet** [comment]
されてるように見える https://github.com/lambdalisue/django-inspectional-registration/blob/develop/src/registration/locale/ja/LC_MESSAGES/django.po#L151

**Comment by lambdalisue** [comment]
あれ、なんでだろう

**Comment by lambdalisue** [comment]
stg でもなってる？メッセージ再コンパイルで治らね？

**Comment by giginet** [comment]
なってる

デプロイの度にcompilemessagesしてる気がする

**Comment by giginet** [comment]
https://github.com/giginet/Geofront/blob/020852ee5709548879c91d71f7f79aa7aa363aa8/uploader/third_infra/django.py

**Comment by lambdalisue** [comment]
謎。他のはろーからいずされてるよね？（django-inspectional-registration の他部分）

**Comment by giginet** [comment]
されてる

**Comment by giginet** [comment]
https://github.com/giginet/Geofront/blob/020852ee5709548879c91d71f7f79aa7aa363aa8/uploader/third_infra/django.py#L38

**Comment by lambdalisue** [comment]
なぜここだけ……

**Comment by lambdalisue** [comment]
```python
class RegistrationFormTermsOfService(RegistrationForm):
    """
    Subclass of ``RegistrationForm`` which adds a required checkbox for
    agreeing to a site's Terms of Service.
    """
    tos = forms.BooleanField(widget=forms.CheckboxInput(attrs=attrs_dict),
                             label=_('I have read and agree to the Terms '
                                     'of Service'),
                             error_messages={'required': _(
                                 "You must agree to the terms to register")})
```
https://github.com/lambdalisue/django-inspectional-registration/blob/develop/src/registration/forms.py#L140-L150

```
#: src/registration/forms.py:146
msgid "I have read and agree to the Terms of Service"
msgstr "サービス利用規約を読み同意します"

#: src/registration/forms.py:149
msgid "You must agree to the terms to register"
msgstr "利用規約に同意する必要があります"
```
https://github.com/lambdalisue/django-inspectional-registration/blob/develop/src/registration/locale/ja/LC_MESSAGES/django.po#L149-L155

謎だ…… どちらかというとここだけ LOCALE が C になってるとかかな

**Comment by giginet** [comment]
ローカル含めて調査してみます

**Comment by tunacook** [comment]
日本語環境だけど再現してない

![](https://gyazo.com/75ecbd5f6a90201d98899669bf4b8cfa.png)

**Comment by giginet** [comment]
🎉
