### ISSUE TITLE
環境構築時にgoogle-api-python-clientが入らない

### ISSUE THREAD

**Issue by tunacook** [kawazrepos/Kawaz3rd#991]
`$ pip install -r config/requirements.txt` する際にconfig/requirements.txtの20行目（google-api-python-client）が入らず、起動時にgoogle-api-python-clientがないと怒られてテストで死んで起動できない

手動でgoogle-api-python-clientを入れるとちゃんと動くので `config/requirements.txt` の記述方法の問題？

**Comment by giginet** [comment]
同じ設定でCIも通ってるので、環境の問題な気がする。
要調査

**Comment by giginet** [comment]
そもそも今まで使ってたfork先の奴がメンテされていない感じがしたので廃止
公式の物がちゃんとテストされていないが3に対応しているようなのでこれに差し替える

https://github.com/kawazrepos/Kawaz3rd/pull/992

**Comment by lambdalisue** [comment]
ok.
