### ISSUE TITLE
ブログ書くページの保存ボタンの位置がおかしい

### ISSUE THREAD

**Issue by tunacook** [kawazrepos/Kawaz3rd#996]
![5fc16320f785d6158deeba819f71d102](https://cloud.githubusercontent.com/assets/1044064/11605086/0b78bc12-9b3a-11e5-8c09-3bdc8e128b9a.png)

左寄せでよさそう

**Comment by giginet** [comment]
これな。いつからおかしくなったんだろう･･････

**Comment by giginet** [comment]
ぎぎにゃん [16:51] 
すぐに直せとは言わないけど

​[16:51] 
何かやる気になったら優先的にやった方が良さそう

​[16:51] 
という温度感

tunacook [16:51] 
OK

ぎぎにゃん [16:51] 
そういうときに適切なラベルがないからパターン青つけてみたｗ
